feat(feature-flag): add feature flag for Circle
thematters/matters-web pull request #1783
Opened 2021-01-28 09:41 UTC by devformatters

2021-01-29 05:35 UTC, robertu7 requested changes

2021-01-29 05:35 UTC, robertu7 commented on src/views/ArticleDetail/EditMode/index.tsx
> +          {toggleCircle && features.circle_management && (
Forgot adding  `features.circle_management` at `<BottomBar>` L236?

2021-01-29 05:35 UTC, robertu7 commented on src/components/Hook/useFeatures.ts
> +export const useFeatures = () => {
Nice abstraction, would it be good if applying to the rest of the places, don't leave legacy :)

2021-02-01 09:53 UTC, devformatters commented on src/views/ArticleDetail/EditMode/index.tsx
> +          {toggleCircle && features.circle_management && (
Totally missed it. Now add it.

2021-02-01 09:53 UTC, devformatters commented on src/components/Hook/useFeatures.ts
> +export const useFeatures = () => {
Done.

2021-02-02 06:06 UTC, robertu7 approved these changes

2021-02-02 07:10 UTC, merged