WIP: feat(invitation): add entrance of invitation list
thematters/matters-web pull request #1923
Opened 2021-03-25 08:48 UTC by devformatters

2021-03-26 10:19 UTC, robertu7 requested changes

2021-03-26 10:19 UTC, robertu7 commented on src/components/CircleInvitation/Invitee.tsx
> +      return <UserDigest.Blank user={user} hasAvatar disabled />
Actually, `<UserDigest.Mini>` has the same UI supports, just pass `user.email` as `user.displayName` with [`toUserDigestMiniPlaceholder`](https://github.com/thematters/matters-web/blob/develop/src/components/SearchSelect/SearchingArea/index.tsx#L283):

```tsx
<UserDigest.Mini user={toUserDigestMiniPlaceholder(user.email)} />
```

2021-03-29 02:48 UTC, devformatters commented on src/components/CircleInvitation/Invitee.tsx
> +      return <UserDigest.Blank user={user} hasAvatar disabled />
That's cool. Replace `Mini` with `Blank`, and remove `Blank` from component and stories.

2021-03-29 02:51 UTC, robertu7 approved these changes
LGTM

2021-03-29 02:52 UTC, merged