Fix accessibility bugs.
thematters/matters-web pull request #2159
Opened 2021-08-02 13:35 UTC by FledgeXu

relative: #2158
This PR fixed the bug which is that VoiceOver can not read the Appreciation count and Donation Count.

2021-08-02 14:31 UTC, robertu7 requested changes
Congrats on creating your first PR!

I have left some comments, please check. 

BTW, `package-lock.json` was changed, please make sure you are running the right versions of node (12.x) & npm (6.x) and reinstall packages (`npm i`).

2021-08-02 14:31 UTC, robertu7 commented on src/common/enums/text.ts
> +    appreciate: '讚賞作品',
please also add `zh_hans` and `en` versions of translations. In this PR, I believe it's overkill to move the aria text to `enums/text.ts` since it's for reusable translations, also, we haven't added i18n support for aria.

2021-08-02 14:31 UTC, robertu7 commented on src/views/ArticleDetail/AppreciationButton/AppreciateButton.tsx
> +        aria-label={`${TEXT.zh_hant.appreciate} ${
Could it add to inside [count text](https://github.com/thematters/matters-web/blob/7240933f082fc806ac64c60b7cea4da335901bba/src/views/ArticleDetail/AppreciationButton/AppreciateButton.tsx#L75) directly? "讚賞作品" is descriptive text of the action button, mixes with "讚賞數量: XXX" seems not intuitive enough?

2021-08-02 14:31 UTC, robertu7 commented on src/views/ArticleDetail/Toolbar/DonationButton/index.tsx
> +              TEXT.zh_hant.donationCount
Same as above.

2021-08-02 22:36 UTC, FledgeXu commented on src/common/enums/text.ts
> +    appreciate: '讚賞作品',
This can move back.

2021-08-02 22:47 UTC, FledgeXu commented on src/views/ArticleDetail/AppreciationButton/AppreciateButton.tsx
> +        aria-label={`${TEXT.zh_hant.appreciate} ${
`aria-label` actually is more like a description of what we can see of an element.  
In this case, We actually can see two different parts: `讚賞作品`  and the number of `讚賞作品`.
![image](https://user-images.githubusercontent.com/16664654/127932241-cff92707-f172-41d0-b377-0d1f01810cab.png)
When we added it, it will look like this:
![image](https://user-images.githubusercontent.com/16664654/127932865-aed35232-f744-42ce-8fd3-45bb7e892cd4.png)

2021-08-02 22:47 UTC, FledgeXu commented on src/views/ArticleDetail/Toolbar/DonationButton/index.tsx
> +              TEXT.zh_hant.donationCount
Same as above.

2021-08-03 02:54 UTC, robertu7 approved these changes

2021-08-03 02:56 UTC, merged