Feat/support feedback
thematters/matters-web pull request #2868
Opened 2022-10-31 07:25 UTC by pitb2022

2022-10-31 13:12 UTC, robertu7 requested changes

2022-10-31 13:12 UTC, robertu7 commented on src/components/Forms/PaymentForm/Processing/index.tsx
> -    await data.wait()
any reason to remove the tx confirmation?

2022-10-31 13:12 UTC, robertu7 commented on src/views/ArticleDetail/SupportWidget/Animation.tsx
> +import { useInView } from 'react-intersection-observer'
I think we can resue `react-waypoint` instead?

https://github.com/thematters/matters-web/blob/develop/package.json#L107

2022-11-01 08:58 UTC, pitb2022 commented on src/views/ArticleDetail/SupportWidget/Animation.tsx
> +import { useInView } from 'react-intersection-observer'
👌

2022-11-04 14:50 UTC, robertu7 requested changes

2022-11-04 14:55 UTC, robertu7 requested changes

2022-11-04 14:55 UTC, robertu7 commented on src/views/ArticleDetail/SupportWidget/index.tsx
>      <section className={supportWidgetClasses}>
border radius is not correct as design.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/4065233/200005834-0b2adc35-6ecf-468f-8f0f-eee6867514b7.png">

2022-11-07 02:09 UTC, pitb2022 commented on src/views/ArticleDetail/SupportWidget/Donators/index.tsx
> +                              width: '1.25rem',
<animated.Avatar> need these styles to align other avatar

2022-11-07 06:08 UTC, robertu7 approved these changes

2022-11-07 09:37 UTC, merged