feat(support-setting): add support setting UI
thematters/matters-web pull request #2890
Opened 2022-11-08 06:43 UTC by Jasmine-liang

2022-11-08 08:42 UTC, robertu7 requested changes

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/ToggleAccess/SetSupportSetting/Content.tsx
> +      <Tab tabType={tabType} setTabType={changeTabType} />
should we put `<Tab>` into below `<Dialog.Content>`?

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/ToggleAccess/SetSupportSetting/SupportPreview.tsx
> +    <section className="donation">
border-radius and spacing is not same as design, please confirm.

<img width="133" alt="image" src="https://user-images.githubusercontent.com/4065233/200509643-b46ba592-6ed2-4903-8200-12651810a363.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/4065233/200509735-51591ec3-aa3f-4fce-a3de-433569f3cf4b.png">

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/ToggleAccess/SetSupportSetting/SupportPreview.tsx
> +                zh_hant="喜歡我的創作嗎？創作並不容易，別忘了給予支持與讚賞，讓我知道在創作的路上有你陪伴。"
I think these fallback copies should be reusable with article detail's? 

cc @pitb2022

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/ToggleAccess/SetSupportSetting/SupportPreview.tsx
> +                />{' '}
`{' '}`?

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/ToggleAccess/SetSupportSetting/SupportPreview.tsx
> +                  zh_hant="感謝 Matty 的支持 🥳，創作這條路不容易，有你的支持我將能夠蓄積更多能量創作。"
hardcoded `Matty`? Please confirm with PM.

2022-11-08 08:42 UTC, robertu7 commented on src/common/utils/form/validate.ts
> +  if (value) {
please use [return-early pattern](https://medium.com/swlh/return-early-pattern-3d18a41bba8)

```ts
if (!value) return

if (value.length > 140) {
   ...
}
```

2022-11-08 08:42 UTC, robertu7 commented on src/components/Button/index.tsx
> -  | 'black'
any reason to remove this prop?

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/BottomBar/index.tsx
> +  displayName,
can just pass down a `user` object if `displayName` and `avatar` is literally from `user`.

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/SettingsDialog/index.tsx
> +    // TODO: support feedback
delete dead code?

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/ToggleAccess/SetSupportSetting/Content.tsx
> +  const formId = 'edit-profile-form'
`support-setting-form`?

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/ToggleAccess/SetSupportSetting/Content.tsx
> +      } catch (error) {
Since `editSupportSetting` is async and we haven't use `await` (we shouldn't), there is no possible to catch errors here. Should error handling in parent component?

2022-11-08 08:42 UTC, robertu7 commented on src/components/Editor/ToggleAccess/SetSupportSetting/Content.tsx
> +            style={{ lineHeight: '1.5rem' }}
same as above comment.

2022-11-08 09:29 UTC, Jasmine-liang commented on src/components/Editor/ToggleAccess/SetSupportSetting/SupportPreview.tsx
> +                />{' '}
That's what linting does 🤔

2022-11-08 10:26 UTC, Jasmine-liang commented on src/components/Editor/ToggleAccess/SetSupportSetting/Content.tsx
> +            style={{ lineHeight: '1.5rem' }}
The lineHeight inherited is 1rem so... Would there be any better ways to change it?

2022-11-09 01:45 UTC, robertu7 requested changes

2022-11-09 01:45 UTC, robertu7 commented on src/components/Editor/BottomBar/index.tsx
> +  viewer,
please clean up unused `viewer`, same below.

2022-11-09 02:39 UTC, robertu7 approved these changes

2022-11-09 02:43 UTC, merged