feat(supporter-ranking-list): add analytics nav-item to my page
thematters/matters-web pull request #2913
Opened 2022-11-11 08:58 UTC by Jasmine-liang

2022-11-14 12:39 UTC, robertu7 requested changes

2022-11-14 12:39 UTC, robertu7 commented on src/views/Me/Analytics/EmptyAnalytics/index.tsx
> +      <Card spacing={['loose', 'base']} bgColor="white" borderRadius="base">
You shouldn't use the `<Card>` component since it's for interactive elements.

2022-11-14 12:39 UTC, robertu7 commented on src/views/Me/Analytics/EmptyAnalytics/styles.css
> +  padding-top: 1rem;
* use CSS variables: `var(--spacing-*)`
* it's 24px?

<img width="272" alt="image" src="https://user-images.githubusercontent.com/4065233/201659670-d5a920a8-5071-415a-b3ab-0eeb85c2b160.png">

2022-11-14 12:39 UTC, robertu7 commented on src/views/Me/Analytics/EmptyAnalytics/index.tsx
> +            href={PATHS.HOME}
To home or to create draft?

2022-11-15 02:20 UTC, Jasmine-liang commented on src/views/Me/Analytics/EmptyAnalytics/index.tsx
> +      <Card spacing={['loose', 'base']} bgColor="white" borderRadius="base">
Confirmed with designer: [new design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=9682%3A52644&t=IdcuahEYzN2yLnAs-0) of desktop

2022-11-15 09:00 UTC, robertu7 requested changes

2022-11-15 09:00 UTC, robertu7 commented on src/views/Me/Analytics/index.tsx
> +  const rangeEnd = rangeStart === null ? null : new Date(Date.now()).toISOString
same as above

2022-11-15 09:03 UTC, robertu7 requested changes

2022-11-15 09:03 UTC, robertu7 commented on src/views/Me/Analytics/index.tsx
> +  const articleCount = data?.viewer?.articles.totalCount
`const articleCount = data?.viewer?.articles.totalCount || 0` since it could be undefined?

2022-11-16 02:32 UTC, robertu7 requested changes

2022-11-16 02:32 UTC, robertu7 commented on src/views/Me/Analytics/SelectPeriod/index.tsx
> +          <TextIcon spacing="base" size="md" weight="normal" color="grey">
For dropdown, can it use the same styles as [`LanguageSwitch`](https://github.com/thematters/matters-web/blob/develop/src/components/Buttons/LanguageSwitch/index.tsx#L34-L38) (for UI consistency)?

2022-11-16 02:32 UTC, robertu7 commented on src/views/Me/Analytics/SupporterDigestFeed/index.tsx
> +          <LinkWrapper {...path} textActiveColor="green">
resolved? so couldn't reuse `<UserDigest.Mini>` right?

2022-11-16 02:32 UTC, robertu7 commented on src/views/Me/Analytics/index.tsx
> +      analytics {
I found you use "All time" as the default query, it seems not what the product wants? 

Try this for querying total count of all donations,

```gql
      analytics {
        allDonations: topDonators(
          input: { first: 0, filter: { inRangeStart: null, inRangeEnd: null } }
        ) {
          totalCount
        }
        topDonators(input: { first: 10, after: $after, filter: $filter }) {
          pageInfo {
            startCursor
            endCursor
            hasNextPage
          }
         ...
```

2022-11-16 02:32 UTC, robertu7 commented on src/views/Me/Analytics/index.tsx
> +      analytics {
https://mattersnews.slack.com/archives/C88CK7Q7L/p1668514205502499?thread_ts=1668501293.263729&cid=C88CK7Q7L

2022-11-16 02:32 UTC, robertu7 commented on src/views/Me/Analytics/styles.css
> +.container {
I believe the list items should be full width as circle analytics does since it's back to old design.

<img width="785" alt="image" src="https://user-images.githubusercontent.com/4065233/202069311-6b893bb9-eecc-4de8-aa38-b276dbd806e1.png">

2022-11-16 06:36 UTC, robertu7 approved these changes

2022-11-16 06:37 UTC, merged