Feat/revise search detail page
thematters/matters-web pull request #2982
Opened 2022-12-14 12:20 UTC by pitb2022

2022-12-14 13:25 UTC, robertu7 requested changes

2022-12-14 13:25 UTC, robertu7 commented on src/views/Search/AggregateResults/Tags.tsx
> +      type: 'search_article',
`search_tag`?

2022-12-14 13:25 UTC, robertu7 commented on src/views/Search/AggregateResults/Users.tsx
> +      type: 'search_article',
`search_user`?

2022-12-14 13:25 UTC, robertu7 commented on src/views/Search/AggregateResults/index.tsx
> +      <Tabs>
spacing isn't same as the design

<img width="469" alt="image" src="https://user-images.githubusercontent.com/4065233/207606233-97cafc97-fda1-4c53-ae63-9d7913feefc7.png">

<img width="506" alt="image" src="https://user-images.githubusercontent.com/4065233/207606342-3a19f940-0e59-40dd-8769-ea3d43b6238d.png">

2022-12-14 13:25 UTC, robertu7 commented on src/components/Search/SearchBar/index.tsx
> +                  onClick={() => {
can use Formik's `setValues` instead?

2022-12-15 05:57 UTC, pitb2022 commented on src/components/ArticleDigest/Concise/index.tsx
> +      <section>
Only show created time

2022-12-15 06:48 UTC, robertu7 approved these changes

2022-12-15 06:52 UTC, merged