Feat/e2e user test
thematters/matters-web pull request #3162
Opened 2023-02-14 08:51 UTC by pitb2022

2023-02-14 09:11 UTC, robertu7 requested changes

2023-02-14 09:11 UTC, robertu7 commented on tests/mutateUser.spec.ts
> +      const unfollowCount = await bobPage
Since the follower count is updated [locally first](https://github.com/thematters/matters-web/blob/develop/src/components/Buttons/FollowUser/Unfollow.tsx#L34-L49), shall we reload the page and see if it's actually updated?

2023-02-14 09:11 UTC, robertu7 commented on tests/mutateUser.spec.ts
> +  ])
Need to check the button UI state (if it becomes to `Unfollow` button)?

2023-02-14 09:11 UTC, robertu7 commented on tests/mutateUser.spec.ts
> +  ])
Check the button UI state (if it becomes to `Follow` button)?

2023-02-15 07:42 UTC, pitb2022 commented on tests/mutateUser.spec.ts
> +      const unfollowCount = await bobPage
done

2023-02-15 08:13 UTC, robertu7 approved these changes

2023-02-15 08:37 UTC, merged