WIP: Website UI Revision Pt.1
thematters/matters-web pull request #3319
Opened 2023-03-31 03:19 UTC by robertu7

* revise homepage `<Announcements>`;

2023-03-31 04:51 UTC, robertu7 commented on src/components/CircleDigest/Plain/styles.css
> +  /* FIXME: fix cropped descenders of letters  */
https://stackoverflow.com/questions/63977541/descenders-of-letters-get-cropped-out-when-using-webkit-line-clamp-with-reduced

2023-04-10 08:09 UTC, pitb2022 requested changes

2023-04-10 08:09 UTC, pitb2022 commented on src/components/CircleDigest/Plain/styles.css
> +  /* FIXME: fix cropped descenders of letters  */
Fix in <TextIcon />
https://github.com/thematters/matters-web/blob/develop/src/components/TextIcon/styles.css#L29#L39

2023-04-11 02:26 UTC, pitb2022 approved these changes

2023-04-11 02:54 UTC, merged