Feat/revise image component
thematters/matters-web pull request #3332
Opened 2023-04-11 08:55 UTC by pitb2022

2023-04-11 10:46 UTC, robertu7 requested changes

2023-04-11 10:46 UTC, robertu7 commented on .env.dev
> +NEXT_PUBLIC_LEGACY_ASSET_DOMAIN=assets-develop.matters.news
can also update to `.env.local.example`

2023-04-11 10:46 UTC, robertu7 commented on src/common/utils/text/article.ts
> -          type="image/webp"
L102-L106 are duplicated with L108-L112

2023-04-11 10:46 UTC, robertu7 commented on src/components/ResponsiveImage/index.tsx
> -            type="image/webp"
Same duplication issue as above.

2023-04-12 02:58 UTC, pitb2022 commented on .env.dev
> +NEXT_PUBLIC_LEGACY_ASSET_DOMAIN=assets-develop.matters.news
done

2023-04-12 02:59 UTC, pitb2022 commented on src/common/utils/text/article.ts
> -          type="image/webp"
Removed

2023-04-12 02:59 UTC, pitb2022 commented on src/components/ResponsiveImage/index.tsx
> -            type="image/webp"
Removed

2023-04-14 05:35 UTC, merged