Feat/revise forms and cells
thematters/matters-web pull request #3359
Opened 2023-04-17 11:51 UTC by pitb2022

2023-04-17 17:07 UTC, robertu7 requested changes

2023-04-17 17:09 UTC, robertu7 commented
Cell is a bit weird on login/signup form...can you confirm with designer?

<img width="459" alt="image" src="https://user-images.githubusercontent.com/4065233/232559100-9beffb40-0367-467b-b45d-fd80c59a1c27.png">

2023-04-18 02:19 UTC, pitb2022 commented on src/components/Form/List/styles.css
>  }
Next PR

2023-04-18 02:32 UTC, pitb2022 commented on src/common/styles/mixins.css
> +    border-color: var(--color-grey);
done

2023-04-18 02:33 UTC, pitb2022 commented on src/components/Form/List/styles.css
>  }
Next PR

2023-04-18 02:34 UTC, pitb2022 commented on src/views/Me/Wallet/styles.css
>      margin-bottom: var(--spacing-loose);
NEXT PR

2023-04-18 06:04 UTC, pitb2022 commented on src/common/styles/mixins.css
> +  color: var(--color-grey-dark);
yes, still black and the grey-dark is for placeholder,

2023-04-18 06:04 UTC, pitb2022 commented on src/components/Form/List/Item/index.tsx
> +      <section className="container" ref={hoverRef}>
done

2023-04-21 06:23 UTC, robertu7 commented on src/components/Form/List/styles.css
> +  /* Fix <DropdownDialog /> contain <Form.List.Item />, when click dropdown
@pitb2022 please take a look at this comment

2023-04-24 10:17 UTC, robertu7 approved these changes

2023-04-24 10:19 UTC, merged