Feat/revise UI
thematters/matters-web pull request #3389
Opened 2023-04-26 12:43 UTC by pitb2022

2023-04-26 16:39 UTC, robertu7 requested changes

2023-04-26 16:39 UTC, robertu7 commented on src/components/Buttons/ViewMoreCard/index.tsx
> -      <Card spacing={['base', 'base']} {...cardProps}>
<img width="466" alt="image" src="https://user-images.githubusercontent.com/4065233/234641334-8cfcc423-403b-4962-a54d-ca7d619ea3f8.png">

wrong spacing between button and card below?

2023-04-26 16:39 UTC, robertu7 commented on src/views/Circle/Works/Works.tsx
> -                  onClickAuthor={() => {
hmm, why remove this?

2023-04-26 16:39 UTC, robertu7 commented on src/views/Me/Wallet/index.tsx
> +              <hr className="dashed-line" />
I didn't get why we need to add the `<hr>` ?

2023-04-27 03:02 UTC, pitb2022 commented on src/views/Circle/Works/Works.tsx
> -                  onClickAuthor={() => {
We had hide author of the article card of the circle

2023-04-27 04:02 UTC, robertu7 approved these changes

2023-04-27 04:04 UTC, merged