Feat/create collect dialog
thematters/matters-web pull request #3600
Opened 2023-07-07 02:10 UTC by pitb2022

2023-07-07 03:53 UTC, robertu7 requested changes

2023-07-07 03:53 UTC, robertu7 commented on src/components/CollectionDigest/DropdownActions/EditCollection/Dialog/Content.tsx
> +          if (code === 'DISPLAYNAME_INVALID') {
There is no `DISPLAYNAME_INVALID` error on this mutation

2023-07-07 03:53 UTC, robertu7 commented on src/components/Dialogs/AddCollectionsArticleDialog/index.tsx
> +  collections?.edges?.forEach(({ node }) => {
`filter` is simpler?

2023-07-07 03:53 UTC, robertu7 commented on src/components/Dialogs/AddCollectionsArticleDialog/index.tsx
> +  collections?.edges?.forEach(({ node }) => {
@gary02 we need a more efficient way to check if a article in a collection or not. For instance, add a `Collection.contains(ID!): Boolean`;

So client-side can query like:
```
...
collections(...) {
    edges {
        node {
            contains(input: { id: $id })
        }
    }
}
...
```

2023-07-07 03:53 UTC, robertu7 commented on src/components/Dialogs/AddCollectionsArticleDialog/index.tsx
> +        toast.success({
Do we still need to show the `message` but only show the `actions` when `checked.length === 1`? Please confirm with design.

2023-07-07 03:53 UTC, robertu7 commented on src/components/Dialogs/AddCollectionsArticleDialog/index.tsx
> +              htmlHref: path.href,
new tab or redirect in current tab?

2023-07-07 03:53 UTC, robertu7 commented on src/components/Dialogs/AddCollectionsArticleDialog/index.tsx
> +                    <Form.SquireCheckBox
typo? square?

2023-07-07 03:53 UTC, robertu7 commented on src/components/Dialogs/AddCollectionsArticleDialog/index.tsx
> +        {inCreatingArea && (
i would prefer to break step dialogs into different component file instead of single.

2023-07-07 03:53 UTC, robertu7 commented on src/components/FileUploader/CoverUploader/index.tsx
> +              <Book
missing loading state for book cover uploading

2023-07-07 03:53 UTC, robertu7 commented on src/components/Form/SquireCheckBox/index.tsx
> +const SquireCheckBox: React.FC<SquireCheckBoxProps> = ({
typo, square

2023-07-07 03:53 UTC, robertu7 commented on src/components/Form/SquireCheckBox/index.tsx
> +      <Tooltip content={hint}>
can move `<Tooltip>` outside of this component or make it optional?

2023-07-07 03:53 UTC, robertu7 commented on src/views/User/CollectionDetail/gql.ts
> +    title
redundant `title`

2023-07-07 03:53 UTC, robertu7 commented on src/views/User/Collections/UserCollections.tsx
> +  const shareSource = getQuery(URL_QS.SHARE_SOURCE_ONBOARDING_TASKS.key)
no need for this

2023-07-07 04:20 UTC, robertu7 requested changes

2023-07-07 04:20 UTC, robertu7 commented on lang/zh-Hans.json
> +    "defaultMessage": "{date}更新",
missing a space between `{date}` and `更新`, same as zh-Hant

2023-07-07 06:18 UTC, pitb2022 commented on src/components/CollectionDigest/DropdownActions/DeleteCollection/Dialog.tsx
> +    setTimeout(() => {
Yes, otherwise it will flash back to the first step of the text

2023-07-07 06:45 UTC, pitb2022 commented on lang/zh-Hans.json
> +    "defaultMessage": "{date}更新",
Chinese design draft without spaces

2023-07-10 10:03 UTC, robertu7 requested changes

2023-07-10 10:03 UTC, robertu7 commented on src/views/User/CollectionDetail/styles.module.css
> +  }
incorrect description color

<img width="745" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/f404a6a1-8fce-4e9e-b280-e8245d6ce193">

2023-07-10 10:08 UTC, robertu7 commented on src/components/Dialogs/AddCollectionsArticleDialog/SelectDialogContent.tsx
> +          <section className={styles.newCollection} onClick={switchToCreating}>
incorrect spacing

<img width="396" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/ac05a7c1-757d-469e-9e57-0a373bc80a25">

2023-07-10 10:13 UTC, robertu7 approved these changes

2023-07-10 14:42 UTC, robertu7 commented on src/components/Form/SquareCheckBox/index.tsx
> +  const fieldId = `field-${inputProps.name}`
https://matterslab.slack.com/archives/C88CK7Q7L/p1688984562975969?thread_ts=1688695871.467379&cid=C88CK7Q7L

2023-07-10 14:43 UTC, robertu7 commented on src/components/Dialogs/AddCollectionsArticleDialog/SelectDialogContent.tsx
> +  checkingIds: string[]
has to reset `checkingIds` on close dialog

https://matterslab.slack.com/archives/C88CK7Q7L/p1688983976340989?thread_ts=1688695871.467379&cid=C88CK7Q7L

2023-07-11 03:42 UTC, merged