Feat/sign in with email
thematters/matters-web pull request #3763
Opened 2023-08-22 09:09 UTC by pitb2022

2023-08-22 09:30 UTC, robertu7 requested changes

2023-08-22 09:30 UTC, robertu7 commented on src/components/Forms/EmailLoginForm/index.tsx
> +            setFieldError('email', m)
please confirm if showing the same error message on both email and password fields is correct.

2023-08-22 09:30 UTC, robertu7 commented on src/components/Forms/EmailLoginForm/index.tsx
> +    setCountdown(10)
60s?

2023-08-22 09:30 UTC, robertu7 commented on src/components/Forms/EmailLoginForm/index.tsx
> +  useEffect(() => {
can we reuse the `useCountdown` hook (also used by `src/components/Forms/Verification/SendCodeButton/index.tsx`)

2023-08-22 09:30 UTC, robertu7 commented on src/components/Form/Input/index.tsx
> +              {rightButton}
need some space between input and `rightButton`

<img width="369" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/cfb8d8b2-d00f-42e0-be40-31c39fbb043b">

2023-08-22 09:30 UTC, robertu7 commented on src/components/Form/Input/index.tsx
> +        {!rightButton && (
Can we combine `right &&` and `!right &&` conditional statements (keep the L78-L95 and remove L97-L113)?

2023-08-23 09:11 UTC, pitb2022 commented on src/components/Forms/EmailLoginForm/index.tsx
> +            setFieldError('email', m)
yes

2023-08-23 09:32 UTC, robertu7 approved these changes

2023-08-24 02:13 UTC, merged