WIP: Improve error handling
thematters/matters-web pull request #3799
Opened 2023-09-11 07:01 UTC by robertu7

* move copies of error messages to formatjs;

2023-09-11 10:05 UTC, pitb2022 requested changes

2023-09-11 10:05 UTC, pitb2022 commented on src/components/Forms/EmailLoginForm/index.tsx
> +                'This login code is invalid, please try to resend',
Copy: Incorrect email or password
ref: https://www.figma.com/file/IbbP1A5KbQTZiIfLAB6Sjq/%E8%A8%BB%E5%86%8A%E8%88%87%E7%99%BB%E5%85%A5?type=design&node-id=979-12075&mode=dev

2023-09-11 10:05 UTC, pitb2022 commented on src/components/Forms/EmailLoginForm/index.tsx
>              setFieldError('password', m)
Also need `setFieldError('email', m)`

2023-09-12 02:17 UTC, robertu7 commented on src/components/Forms/EmailLoginForm/index.tsx
> +                'This login code is invalid, please try to resend',
this error message is correspond to `USER_EMAIL_NOT_FOUND` or `USER_PASSWORD_INVALID`, which will be fallback to the global errors and catched by [L190](https://github.com/thematters/matters-web/pull/3799/files/9d39782bad2e68c71f4c6bdb4a2d960703940aee#diff-75e6bc3748ce6a3d7c456823eca575fbb2e105c50ed29abc326eaa8d7cc5bea4R190):


```ts
else {
  setFieldError('password', intl.formatMessage(messages[code]))
}
```

2023-09-12 08:41 UTC, pitb2022 approved these changes

2023-09-13 04:23 UTC, merged