feat(username): force `userNameEditable` user to confirm the username
thematters/matters-web pull request #3812
Opened 2023-09-14 09:32 UTC by robertu7

2023-09-14 10:34 UTC, pitb2022 requested changes

2023-09-14 10:34 UTC, pitb2022 commented on src/components/Dialogs/SetEmailDialog/Content.tsx
> +        await set({ variables: { input: { email } } })
need update user.info.email、user.info.emailVerified

2023-09-14 16:21 UTC, robertu7 commented on src/components/Dialogs/SetEmailDialog/Content.tsx
> +        await set({ variables: { input: { email } } })
should be fixed

2023-09-15 05:07 UTC, pitb2022 approved these changes

2023-09-15 05:29 UTC, merged