feat(CollectionDetail): add sequence sorter
thematters/matters-web pull request #3821
Opened 2023-09-18 06:20 UTC by pitb2022

2023-09-18 07:01 UTC, robertu7 requested changes

2023-09-18 07:01 UTC, robertu7 commented on src/common/enums/url.ts
> +    value: { normal: 'normal', reverse: 'reverse' },
`date-asc` and `date-dsc` for further extensibility (if we support more sorting methods)

2023-09-18 07:01 UTC, robertu7 commented on src/views/User/CollectionDetail/CollectionArticles/index.tsx
> +  useEffect(() => {
comments on Slack

2023-10-05 03:33 UTC, pitb2022 commented on src/common/enums/url.ts
> +    key: 'sorter-sequence',
Sequence is a linear order, one thing after another. There are other ways of ordering things that are not sequential

2023-10-05 03:35 UTC, pitb2022 commented on src/common/enums/url.ts
> +    value: { normal: 'normal', reverse: 'reverse' },
Now that collection articles are not sorted by date, using date is not a good idea

2023-10-05 09:29 UTC, robertu7 approved these changes
LGTM 🍉

2023-10-05 11:11 UTC, merged