Fix/new login stage 1
thematters/matters-web pull request #3824
Opened 2023-09-19 03:33 UTC by pitb2022

2023-09-19 03:46 UTC, robertu7 requested changes
please double-check the dialog spacing issues

2023-09-19 03:46 UTC, robertu7 commented on src/views/Auth/Universal/index.tsx
> +      <Head />
better to have a title about authentication, please confirm with product team.

2023-09-19 03:46 UTC, robertu7 commented on src/components/Dialogs/SetUserNameDialog/hook.ts
> +import { toLower } from 'lodash'
Use `lodash/toLower` for code splitting or just use `.toLowerCase()`

2023-09-19 08:01 UTC, pitb2022 commented on src/views/Auth/Universal/index.tsx
> +      <Head />
Confirm the use of the default title

2023-09-20 02:07 UTC, robertu7 approved these changes

2023-09-20 02:22 UTC, merged