Fix/new login round ii
thematters/matters-web pull request #3842
Opened 2023-09-24 09:22 UTC by pitb2022

2023-09-24 09:25 UTC, robertu7 commented on src/views/Callback/styles.module.css
> +  height: 100dvh;
`dvh` doesn't support Firefox, should keep the `vh` here:

```
height: 100vh;
height: 100dvh;
```

2023-09-25 01:08 UTC, pitb2022 commented on src/views/Callback/styles.module.css
> +  height: 100dvh;
[CSS API: dvh() static method](https://caniuse.com/mdn-api_css_dvh_static) not support firefox
[types: <length>: dvb, dvh, dvi, dvmax, dvmin, dvw units](https://caniuse.com/mdn-css_types_length_viewport_percentage_units_dynamic) support firefox

2023-09-25 01:32 UTC, robertu7 requested changes

2023-09-25 01:32 UTC, robertu7 commented on src/common/styles/bases/reset.css
> +input:-webkit-autofill:active {
better not to reset this default styles for autofill?

2023-09-25 01:32 UTC, robertu7 commented on src/common/styles/variables/colors.css
> +  --color-grey-scale: #fff9;
"scale" is not a properly name. Also, can you give me the reference of this color since I couldn't find it.

2023-09-25 01:32 UTC, robertu7 commented on src/components/Forms/EmailLoginForm/index.tsx
> -    isSubmitting,
overwrite the <Formik> behavior seems not a good idea, any ideas?

2023-09-25 02:25 UTC, robertu7 commented on src/common/styles/bases/reset.css
> +input:-webkit-autofill:active {
confirming with design on test doc

2023-09-26 07:57 UTC, pitb2022 commented on src/common/styles/bases/reset.css
> +input:-webkit-autofill:active {
Revert

2023-09-26 08:14 UTC, pitb2022 commented on src/common/styles/variables/colors.css
> +  --color-grey-scale: #fff9;
ref: zn-0019

2023-09-26 08:49 UTC, robertu7 commented on src/common/styles/variables/colors.css
> +  --color-grey-scale: #fff9;
this one? 

<img width="615" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/b5dc5f4a-bd44-4f18-9b73-562bbd887557">

for the naming, "scale" means measurement scale, we should name it with a exact level or purpose, e.g. `--color-grey-countdown`

2023-09-29 02:15 UTC, robertu7 requested changes

2023-09-29 02:15 UTC, robertu7 commented on src/components/GQL/hooks.ts
> +    onError: (error) =>
can skip toast here instead of revise `toastMutationErrors`? 

```
onError: (error) => {
    if (!shouldToast) return

    ...
}
```

2023-09-29 02:15 UTC, robertu7 commented on src/components/GQL/hooks.ts
> +    onError: (error) =>
And there is a `ToastMutationErrorsOptions.showToast` here, what's the difference?

2023-09-29 02:15 UTC, robertu7 commented on src/components/Head/index.tsx
> +        key="favicon-64"
`key` should be unique.

2023-09-29 02:15 UTC, robertu7 commented on src/views/Me/Settings/Account/MyProfile/index.tsx
> +    <EditProfileDialog user={viewer}>
so that we can remove the `refetchQueries` on `SetUserNameDialog`, right?

2023-09-29 02:15 UTC, robertu7 commented on src/views/User/UserProfile/AsideUserProfile/index.tsx
> +                  className={styles.meDisplayName}
`role="button"` for a11y

2023-09-29 02:15 UTC, robertu7 commented on src/components/GQL/hooks.ts
> +  const isInCallback = isInPath('CALLBACK_PROVIDER')
not a good idea to hardcode logic here.

2023-10-03 03:05 UTC, pitb2022 commented on src/views/Me/Settings/Account/MyProfile/index.tsx
> +    <EditProfileDialog user={viewer}>
SetUserNameDialog will open not only on the setting page, but also on any other page

2023-10-03 03:55 UTC, pitb2022 commented on src/views/User/UserProfile/AsideUserProfile/index.tsx
> +                  className={styles.meDisplayName}
done

2023-10-03 04:41 UTC, robertu7 approved these changes

2023-10-03 04:41 UTC, robertu7 commented on src/components/GQL/error.tsx
> +    showLoginToast,
default should be `true`？

2023-10-03 05:23 UTC, pitb2022 commented on src/components/GQL/error.tsx
> +    showLoginToast,
yes
https://github.com/thematters/matters-web/pull/3842/commits/8a3091f00722e064b96013917e1f213e4332c05c#diff-16c09ad269f38198f3270d32b3cb75ea127576525d6c726e136cfdbbc5b2eb83R257

2023-10-03 06:53 UTC, merged