feat(upload): adjust gif support
thematters/matters-web pull request #3953
Opened 2023-10-30 14:31 UTC by gary02

resolve https://github.com/thematters/developer-resource/issues/253

2023-10-30 15:08 UTC, robertu7 requested changes

2023-10-30 15:08 UTC, robertu7 commented on src/components/Cover/index.tsx
> +        disableAnimation={true}
this component is used as user profile cover, tag profile cover, etc. and it's supposed to support animated GIF.

2023-10-30 15:08 UTC, robertu7 commented on src/components/TagDigest/Feed/index.tsx
> +                  disableAnimation={true}
please confirm if tag cover support animated GIF in feed.

2023-10-30 15:08 UTC, robertu7 commented on src/components/TagDigest/Sidebar/index.tsx
> +                disableAnimation={true}
please confirm if tag cover support animated GIF in sidebar.

2023-10-31 00:08 UTC, robertu7 requested changes

2023-10-31 00:08 UTC, robertu7 commented on src/common/utils/url.ts
> +  if (disableAnimation) {
can disable by default instead since most of the use cases don't support animated GIF?

2023-10-31 02:05 UTC, gary02 commented on src/common/utils/url.ts
> +  if (disableAnimation) {
I think animation enable by default is a little more safe then disable by default ?

2023-10-31 06:09 UTC, robertu7 approved these changes

2023-11-01 08:37 UTC, merged