Feat/published tab page
thematters/matters-web pull request #3974
Opened 2023-11-06 10:29 UTC by pitb2022

2023-11-06 14:59 UTC, robertu7 requested changes
Overall looks good

2023-11-06 14:59 UTC, robertu7 commented on src/components/ArticleDigest/Published/FooterActions/index.tsx
> +            data-test-id={TEST_ID.DIGEST_ARTICLE_PUBLISHED_READER_COUNT}
could add `aria-label` for a11y

2023-11-06 14:59 UTC, robertu7 commented on src/components/ArticleDigest/Published/FooterActions/index.tsx
> +            data-test-id={TEST_ID.DIGEST_ARTICLE_PUBLISHED_READER_COUNT}
same as below icons

2023-11-06 14:59 UTC, robertu7 commented on src/components/ArticleDigest/Published/FooterActions/styles.module.css
> +      width: 2rem;
38px (2.375rem)?

2023-11-06 14:59 UTC, robertu7 commented on src/views/Me/Works/Published/index.tsx
> +  onFirstLoading()
this will be called on every re-rendering (e.g. load next page of pagination, switch tab)

2023-11-06 14:59 UTC, robertu7 commented on src/views/Me/Works/Published/SortTabs.tsx
> +export const SortTabs = ({
pls confirm whether we should set the sort type to query string: 

```
/me/published?sort=newest
/me/published?sort=most-readers
...
```

2023-11-07 08:13 UTC, pitb2022 commented on src/views/Me/Works/Published/index.tsx
> +  onFirstLoading()
Yes, the code has been refactored to make its purpose easier to understand

2023-11-07 08:52 UTC, pitb2022 commented on src/components/ArticleDigest/Published/FooterActions/index.tsx
> +            data-test-id={TEST_ID.DIGEST_ARTICLE_PUBLISHED_READER_COUNT}
done

2023-11-07 11:35 UTC, robertu7 approved these changes
🚀

2023-11-08 00:57 UTC, merged