Feat/Desktop comment drawer
thematters/matters-web pull request #4192
Opened 2024-02-20 07:31 UTC by pitb2022

2024-02-20 10:08 UTC, robertu7 requested changes

2024-02-20 10:08 UTC, robertu7 commented on src/components/CommentBeta/Feed/styles.module.css
> +  width: 22.5rem;
hardcoded?

2024-02-20 10:08 UTC, robertu7 commented on src/components/CommentBeta/RoleLabel/index.tsx
make a new component `<Label>` in https://github.com/thematters/matters-web/pull/4175/files#diff-ae6c67fe4fcac7f4dcc3460bb2b75856fb91006f00dd172528601935c3a31880, can reuse it later

2024-02-20 10:08 UTC, robertu7 commented on src/components/Forms/CommentFormBeta/index.tsx
same as above, should be replace the `<CommentForm>` 

ref: [discussion](https://matterslab.slack.com/archives/G8877EQMS/p1707314475183879?thread_ts=1707305323.343669&cid=G8877EQMS)

2024-02-21 06:47 UTC, pitb2022 commented on lang/zh-Hans.json
> +    "defaultMessage": "Author",
Has fixed in [next pr](https://github.com/thematters/matters-web/pull/4193)

2024-02-21 06:48 UTC, pitb2022 commented on lang/zh-Hans.json
> +    "defaultMessage": "Supporter",
Has fixed in https://github.com/thematters/matters-web/pull/4193

2024-02-21 06:48 UTC, pitb2022 commented on lang/zh-Hant.json
> +    "defaultMessage": "Author",
Has fixed in https://github.com/thematters/matters-web/pull/4193

2024-02-21 06:50 UTC, pitb2022 commented on lang/zh-Hant.json
> +    "defaultMessage": "Supporter",
Has fixed in https://github.com/thematters/matters-web/pull/4193

2024-02-21 06:56 UTC, pitb2022 commented on src/components/CommentBeta/Feed/styles.module.css
> +  width: 22.5rem;
yes

2024-02-21 06:56 UTC, pitb2022 commented on lang/zh-Hant.json
> +    "defaultMessage": "Comment",
fixed

2024-02-21 07:10 UTC, pitb2022 commented on src/components/CommentBeta/RoleLabel/index.tsx
Has added todo note, will reuse it later

2024-02-22 00:55 UTC, robertu7 commented on lang/en.json
<img width="150" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/750c979e-46cf-4375-8e99-5cd851adc5d6">

2024-02-22 00:59 UTC, robertu7 commented on src/components/CommentBeta/Feed/index.tsx
> +              <DateTime date={comment.createdAt} color="grey" />
there is link with hash (`#`) in legacy component, pls confirm with product if keep it or not

2024-02-27 04:41 UTC, merged