feat(articledetail): add matters logo as back button when display is mobile
thematters/matters-web pull request #4395
Opened 2024-05-16 22:21 UTC by byhow

fix: #4368

2024-05-17 07:52 UTC, robertu7 requested changes

2024-05-17 07:52 UTC, robertu7 commented on public/static/icons/logo-mobile.svg
looks like the same icon as `public/static/icons/logo.svg` except the color? 

can change `fill="#333"` to `fill: currentColor` so that we can specify the color in `<Icon>`.

2024-05-17 07:52 UTC, robertu7 commented on src/views/ArticleDetail/index.tsx
> +          style={{
better to avoid inline styles

2024-05-18 01:12 UTC, byhow commented
comments addressed. new logo now looks like this: 
<img width="364" alt="image" src="https://github.com/thematters/matters-web/assets/25713361/1658dd28-68ca-46eb-a3b1-9e6bba3023f3">

2024-05-18 01:15 UTC, byhow commented on public/static/icons/logo-mobile.svg
nice, thanks for the pointer to the documentation 🙌

2024-05-18 01:15 UTC, byhow commented on src/views/ArticleDetail/index.tsx
> +          style={{
refactored

2024-05-19 01:42 UTC, robertu7 approved these changes
LGTM!

2024-05-20 00:37 UTC, merged