feat(taglist): update text hashtag symbol to actual icon
thematters/matters-web pull request #4433
Opened 2024-05-22 01:07 UTC by byhow

addendum to #4419

2024-05-22 12:50 UTC, robertu7 requested changes
Also left some comments on Slack thread

2024-05-22 12:50 UTC, robertu7 commented on lang/zh-Hans.json
To reuse copies, you can remove the `description` from `<FormatMessage description="..." defaultMessage="..." />`, so that it won't create separate translations after running [`npm run i18n`](https://github.com/thematters/matters-web/blob/develop/package.json#L36).

2024-05-22 12:50 UTC, robertu7 commented on lang/zh-Hant.json
Missing translations

2024-05-22 12:50 UTC, robertu7 commented on lang/zh-Hant.json
same issue as above `lang/zh-Hans.json`

2024-05-22 12:50 UTC, robertu7 commented on src/components/Editor/TagCustomStagingArea/gql.ts
> +  ${tagFragments.tag}
In practice, we export GraphQL fragments from a component.

ref: https://dev.to/ricardoromox/colocated-fragments-organizing-your-graphql-queries-in-react-24a6

2024-05-22 12:55 UTC, robertu7 requested changes

2024-05-22 12:55 UTC, robertu7 commented on src/components/Tag/index.tsx
Shall we break down `src/components/Tag/styles.module.css` into separate CSS files so that the Tag components are self-contained?

```
...
├── ArticleTag
│   ├── styles.module.css
│   ├── ArticleTag.test.tsx
│   └── index.tsx
├── InlineTag
│   ├── styles.module.css
│   ├── InlineTag.test.tex
│   └── index.tsx
└── index.tsx
```

2024-05-23 07:52 UTC, byhow commented on src/components/Editor/TagCustomStagingArea/gql.ts
> +  ${tagFragments.tag}
Thanks, good reference!

2024-05-23 07:57 UTC, byhow commented on lang/zh-Hans.json
Nice, good pointer :)

2024-05-23 07:58 UTC, byhow commented on lang/zh-Hant.json
I reverted to use the default `"Remove"` property in the intl files. Let me know if this is an issue, thanks

2024-05-23 08:54 UTC, byhow commented
Here are some sample tag styles after refactoring icons into text:
## Feed 
<img width="285" alt="feed" src="https://github.com/thematters/matters-web/assets/25713361/af6f8516-4403-439f-8a57-99caf8f12c44">

## Article
<img width="322" alt="image" src="https://github.com/thematters/matters-web/assets/25713361/6d4c6673-5749-46fe-8764-1b6c9db7497f">

## Search
<img width="289" alt="image" src="https://github.com/thematters/matters-web/assets/25713361/56737252-f077-4ba3-b202-fb047284e03e">

## Cover Image
<img width="194" alt="image" src="https://github.com/thematters/matters-web/assets/25713361/6e3e3827-11e9-47d3-a83c-79da62617698">

## Draft add tag
<img width="382" alt="image" src="https://github.com/thematters/matters-web/assets/25713361/ead6f473-c1f9-41f1-9f20-c28e27fe6315">

## Draft Selected Tag
<img width="269" alt="image" src="https://github.com/thematters/matters-web/assets/25713361/e71bf7ae-cee0-4b14-bb29-a318ea9bd8fe">

2024-05-23 12:22 UTC, robertu7 requested changes

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/ArticleTag/index.tsx
> +    spacing: 2,
there is no spacing between text and icon here.

<img width="456" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/25caf2ad-1bbc-4b00-a580-7b317773ccba">


ref: https://www.figma.com/design/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?node-id=5739-77844&m=dev

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/ArticleTag/index.tsx
> +  active?: boolean
Can remove `active` since it should be a default style for `<ArticleTag>`

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/ArticleTag/styles.module.css
> +  &.active {
As comment above, we can merge `.active` styles into `.article`.

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/InlineTag/index.tsx
> +    spacing: 4,
There is no spacing between icon and text.

<img width="443" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/2fce6f67-8fa6-40aa-bdb3-c99e19263435">

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/InlineTag/styles.module.css
> +    margin-left: 3px;
spacing left should be `--sp2` and spacing-right can be removed.

<img width="450" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/6029ca5b-546b-4cad-822e-2532ec09d42d">

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/InlineTag/styles.module.css
> +    margin-left: 3px;
ref: https://www.figma.com/design/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3668-24266&m=dev

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/InlineTag/index.tsx
> +    spacing: 4,
ref: https://www.figma.com/design/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3668-24266&m=dev

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/InlineTag/index.tsx
> +  const tagClasses = classNames({
Please reorg or clean up unused class names as  `is` prop changes mentioned above.

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/TitleTag/index.tsx
Since it's used only once, maybe we can move it to `src/views/TagDetail/Cover`?

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/TitleTag/index.tsx
> +interface TitleTagProps {
can remove unused props.

2024-05-23 12:22 UTC, robertu7 commented on src/components/Tag/TitleTag/index.tsx
> +    [styles.active]: active,
and remove unused class names and styles.

2024-05-23 22:38 UTC, byhow commented on src/components/Editor/Sidebar/Tags/index.tsx
> +                  <InlineTag
Based on the previous type it was `inline` tag. Are there any properties I need to remove?

2024-05-23 22:39 UTC, byhow commented on src/components/Tag/InlineTag/index.tsx
> +          <Icon icon={IconTimes} color="grey" />
Got it, replaced with the above icon.

2024-05-23 22:44 UTC, byhow commented on src/components/Editor/TagCustomStagingArea/SelectedTags/index.tsx
> +            <InlineTag tag={tag} active onRemoveTag={() => onRemoveTag(tag)} />
Got it, would you elaborate on what the redirection is? The previous tag is `inline` type so I wonder what should I get rid of

2024-05-24 00:25 UTC, byhow commented on src/components/Tag/InlineTag/index.tsx
> +  is?: 'a' | 'span'
I kind of see what you mean. So `<InlineTag>` will never be a link? It will always be `<span>` then in this case.

2024-05-24 00:40 UTC, byhow commented on src/components/Editor/Sidebar/Tags/index.tsx
> +                  <InlineTag
nvm, plz see https://github.com/thematters/matters-web/pull/4433#discussion_r1612506388

2024-05-24 01:57 UTC, byhow commented
@robertu7 All comments are addressed and ready for review again. I am not the best person when it comes to CSS so please let me know if there's any issues in the refactoring for that part. Thanks!

2024-05-24 02:13 UTC, robertu7 approved these changes
LGTM!

2024-05-24 03:47 UTC, merged