chore(notice-comment): fix copy issue in PR-2
thematters/matters-web pull request #4497
Opened 2024-05-30 04:41 UTC by byhow

re: #4460

2024-05-30 08:06 UTC, robertu7 requested changes

2024-05-30 08:06 UTC, robertu7 commented on lang/zh-Hans.json
pls correct the translations

2024-05-30 08:06 UTC, robertu7 commented on lang/zh-Hant.json
please correct the translations

2024-05-30 08:06 UTC, robertu7 commented on src/components/Notice/NoticeActorName.tsx
> +        {user.displayName && user.displayName.length > 20
can use `MAX_USER_DISPLAY_NAME_LENGTH` from `utils/enums` instead

2024-05-31 05:16 UTC, byhow commented
@robertu7 Sorry the translation bit passed through, prolly cuz I missed it after it changed after the i18n check or something. Ready for review again!

2024-05-31 05:28 UTC, robertu7 approved these changes

2024-05-31 06:17 UTC, merged