feat(layout): add popover for new journal entry
thematters/matters-web pull request #4516
Opened 2024-06-05 01:38 UTC by byhow

re: #4487
close #4513

2024-06-07 11:53 UTC, robertu7 requested changes

2024-06-07 11:53 UTC, robertu7 commented on src/components/Layout/NavBar/NavBanner.tsx
> +      <div className={styles['notification-text']}>
use camelCase instead of snake_case for CSS class name

2024-06-07 11:53 UTC, robertu7 commented on src/components/Layout/NavBar/NavPopover.tsx
> +        <li key={'new-journal'}>
curly brace is unnecessary

2024-06-07 11:53 UTC, robertu7 commented on src/components/Layout/NavBar/styles.module.css
> +    margin-left: var(--sp24);
<img width="166" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/3eae0a91-d212-431a-bada-afa3aa291d9e">

2024-06-07 11:53 UTC, robertu7 commented on src/components/Layout/NavBar/styles.module.css
> +    font-size: 18px;
`var(--text18)`

2024-06-07 11:53 UTC, robertu7 commented on src/components/Layout/NavBar/styles.module.css
> +    font-weight: 500;
`var(--font-medium)`

2024-06-07 11:53 UTC, robertu7 commented on src/components/Layout/NavBar/styles.module.css
> +      font-size: 14px;
`var(----text14)`

2024-06-07 11:53 UTC, robertu7 commented on src/stories/components/ActivityPopover/ActivityPopover.stories.tsx
> +      theme="mobile"
should be shadow border instead of grey border

<img width="271" alt="image" src="https://github.com/thematters/matters-web/assets/4065233/b2869d56-b8e5-4e8b-b468-1cd7693eb380">

2024-06-08 04:08 UTC, byhow commented on src/components/Layout/NavBar/styles.module.css
> +    margin-left: var(--sp24);
Nice catch! resolved the alignment

2024-06-08 04:09 UTC, byhow commented on src/stories/components/ActivityPopover/ActivityPopover.stories.tsx
> +      theme="mobile"
I think the box shadow mimic the same as `dropdown`. If you are referring to the top border, I am not sure how would that work with the current state of CSS. I tried to use the exact same class here:
https://github.com/thematters/matters-web/pull/4516/files#diff-86d58c4f4ea93cb30bc1b5aed1e1d8b3fa26105d3f3568973c50b2aa2e3f581fL149

2024-06-11 08:22 UTC, robertu7 approved these changes

2024-06-11 08:28 UTC, merged