refactor(article-digest): remove metadata for featured
thematters/matters-web pull request #4614
Opened 2024-07-01 05:32 UTC by byhow

fix https://github.com/thematters/matters-web/issues/4607

2024-07-01 07:38 UTC, robertu7 requested changes

2024-07-01 07:38 UTC, robertu7 commented on src/views/Home/Feed/IcymiCuratedFeed/index.tsx
> +                includesMetaData={false}
`<IcymiCuratedFeed>` is a optional section of ICYMI feed, we should also disable `includesMetaData` for [infinite list for ICYMI feed](https://github.com/thematters/matters-web/blob/develop/src/views/Home/Feed/MainFeed/index.tsx#L228).

2024-07-01 22:10 UTC, byhow commented on src/views/Home/Feed/IcymiCuratedFeed/index.tsx
> +                includesMetaData={false}
cool, thx for the pointer! updated in the latest commit

2024-07-02 00:43 UTC, robertu7 approved these changes

2024-07-02 01:03 UTC, merged