feat(collections): add like button for collections
thematters/matters-web pull request #4646
Opened 2024-07-13 22:25 UTC by byhow

re: #4626

2024-07-29 06:53 UTC, robertu7 requested changes
Please implement as specified in the Figma design

2024-07-30 08:03 UTC, robertu7 approved these changes
Overall looks good

2024-07-30 08:03 UTC, robertu7 commented on src/views/User/CollectionDetail/CollectionProfile/LikeButton/index.tsx
> +  iconSize?: 20 | 22
unused prop `iconSize`?

2024-07-30 08:03 UTC, robertu7 commented on src/views/User/CollectionDetail/CollectionProfile/index.tsx
L87-L96 can be removed?

<img width="580" alt="image" src="https://github.com/user-attachments/assets/b0ca0335-a222-42f7-a9ce-817a66a881fb">

2024-07-30 21:40 UTC, byhow commented on src/views/User/CollectionDetail/CollectionProfile/LikeButton/index.tsx
> +  iconSize?: 20 | 22
This was not used in this component but it is used at L141

2024-07-30 21:56 UTC, merged