feat(notice): collection like
thematters/matters-web pull request #4686
Opened 2024-07-26 07:15 UTC by byhow

re: #4625

2024-07-29 07:05 UTC, robertu7 requested changes

2024-07-29 07:05 UTC, robertu7 commented on src/common/utils/text/collection.ts
> +export const truncateTitle = (
looks similar to ~/utils/text/moment.ts. Can we merge it reusable?

* move to `~/utils/text/notice.ts`;
* rename to `truncateNoticeTitle`;
* add optional param to handle `@` for moment notice title;

2024-07-30 00:19 UTC, byhow commented on src/common/utils/text/collection.ts
> +export const truncateTitle = (
Got it, makes sense, will cherry pick the new commit to `feat/journal` when merged

2024-07-30 05:46 UTC, robertu7 approved these changes

2024-07-30 06:15 UTC, merged